export * from './TArrayElement';
export * from './TDayOfWeek';
export * from './TEntries';
export * from './TNestedObjectPaths';
export * from './TOpeningHours';
export * from './TOpeningHoursData';
export * from './TRestaurantResponse';
export * from './TRestaurantResponseData';
export * from './TRestaurantsResponse';
